name: Example workflow yml

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install python deps
      run: sudo apt-get install python3-setuptools
    - uses: actions/checkout@v1
    - name: Package
      uses: bpicode/github-action-fpm@master
      with:
        fpm_args: './build'
        fpm_opts: '-s python -t deb hyper-shell'

