name: Example workflow yml

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Package
      uses: bpicode/github-action-fpm@master
      with:
        fpm_args: './build'
        fpm_opts: '-s python -t osxpkg hyper-shell'

